apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

buildMetadata: [managedByLabel]

labels:
- pairs:
    commit: a88ea4d
  includeTemplates: true
  includeSelectors: true

images:
- name: chukmunnlee/dov-bear
  newName: chukmunnlee/argo-dov-bear
  digest: sha256:e69b4bb353f9697e5407de03298abbc607d5a6482e4dc9c95f1413c790daf87f
