apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: a88ea4d
  name: playground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: a88ea4d
  name: dov-svc
  namespace: playground
spec:
  ports:
  - port: 3000
    targetPort: dov-port
  selector:
    app: dov-bear
    commit: a88ea4d
    name: dov-po
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dov-bear
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: a88ea4d
    name: dov-deploy
  name: dov-deploy
  namespace: playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dov-bear
      commit: a88ea4d
      name: dov-po
  template:
    metadata:
      labels:
        app: dov-bear
        commit: a88ea4d
        name: dov-po
      name: dov-po
    spec:
      containers:
      - env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: chukmunnlee/argo-dov-bear@sha256:674532923733c25fec354481dd440247319a60dc9225f04dd2701675766d5995
        imagePullPolicy: IfNotPresent
        name: dov-container
        ports:
        - containerPort: 3000
          name: dov-port
