apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: f6a5639
  name: playground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: f6a5639
  name: dov-svc
  namespace: playground
spec:
  ports:
  - port: 3000
    targetPort: dov-port
  selector:
    app: dov-bear
    commit: f6a5639
    name: dov-po
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dov-bear
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: f6a5639
    name: dov-deploy
  name: dov-deploy
  namespace: playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dov-bear
      commit: f6a5639
      name: dov-po
  template:
    metadata:
      labels:
        app: dov-bear
        commit: f6a5639
        name: dov-po
      name: dov-po
    spec:
      containers:
      - env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: chukmunnlee/argo-dov-bear@sha256:105c14e38830204549ed91efae673558a20a10205fde5b8a3be391b5b832ddbc
        imagePullPolicy: IfNotPresent
        name: dov-container
        ports:
        - containerPort: 3000
          name: dov-port
