apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: aa5a1c2
  name: playground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: aa5a1c2
  name: dov-svc
  namespace: playground
spec:
  ports:
  - port: 3000
    targetPort: dov-port
  selector:
    app: dov-bear
    commit: aa5a1c2
    name: dov-po
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dov-bear
    app.kubernetes.io/managed-by: kustomize-v5.4.1
    commit: aa5a1c2
    name: dov-deploy
  name: dov-deploy
  namespace: playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dov-bear
      commit: aa5a1c2
      name: dov-po
  template:
    metadata:
      labels:
        app: dov-bear
        commit: aa5a1c2
        name: dov-po
      name: dov-po
    spec:
      containers:
      - env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: chukmunnlee/argo-dov-bear@sha256:973deb48324fe10f49d1e01e6789927aaece38895a10cb2a019a8dea159b7998
        imagePullPolicy: IfNotPresent
        name: dov-container
        ports:
        - containerPort: 3000
          name: dov-port
