apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: stage
spec:
  ports:
  - port: 3000
    targetPort: dov-port
  selector:
    app: dov-bear
    name: dov-po
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dov-bear
    name: dov-deploy
  name: dov-deploy
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dov-bear
      name: dov-po
  template:
    metadata:
      labels:
        app: dov-bear
        name: dov-po
      name: dov-po
    spec:
      containers:
      - env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: chukmunnlee/argo-dov-bear@sha256:7a2dfc46675aa01c6760bb202f3478c174356061039e87528215fe029d996276
        imagePullPolicy: IfNotPresent
        name: dov-container
        ports:
        - containerPort: 3000
          name: dov-port
