apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: dev
spec:
  ports:
  - port: 3000
    targetPort: dov-port
  selector:
    app: dov-bear
    name: dov-po
  type: ClusterIP
---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: dov-bear
    name: dov-deploy
  name: dov-deploy
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dov-bear
      name: dov-po
  template:
    metadata:
      labels:
        app: dov-bear
        name: dov-po
      name: dov-po
    spec:
      containers:
      - env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: chukmunnlee/argo-dov-bear@sha256:8fb6482e209ff9f5c33ed6b51c35d0a248e569c3a594d37963ae41cfc485583d
        imagePullPolicy: IfNotPresent
        name: dov-container
        ports:
        - containerPort: 3000
          name: dov-port
