apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

buildMetadata: [managedByLabel]

labels:
- pairs:
    commit: d85f714
  includeTemplates: true
  includeSelectors: true

images:
- name: chukmunnlee/dov-bear
  newName: chukmunnlee/argo-dov-bear
  digest: sha256:52e0110d374278cea35a135ce5761ef7b11fc8b21ad80cb17c91b301082ee4db
